### ISSUE TITLE
Strange resize behavior in chapter 1.5: Swapchain recreation

### ISSUE THREAD

**Issue by quixoticaxis** [adrien-ben/vulkan-tutorial-rs#2]
First and foremost, thank you for the great tutorial. I'm currently following it and I've got to the chapter 1.5. When implemented, the code does not enable window resizing (only maximizing and switching back to the original size works). At first I was thinking that it all comes to my own modifications (I'm using the latest version of the libraries, most notably the latest version of `winit`), but after spending some time I failed to grasp the problem and checked out your repository at the corresponding commit - the behavior is the same, only maximized and original sizes are reachable.

Could you please tell me if it's by design?

**Comment by adrien-ben** [comment]
Hi ! 

Well thanks :) The tutorial is not mine by the way, but yeah it's great ! I just implemented a Rust version :)

Indeed that's is weird, I just checked out the code at that same commit and it supports resizing the window. Does it behave the same way on the latest commit from master ?

Also I just tested on Windows, I should be able to try on Linux in a few hours. What OS are you using ?

**Comment by quixoticaxis** [comment]
The latest commit on master draws a white window for me, I can resize it and the original area stays white while the enlarged area stays black. I'm on Windows 10 64 bit with the latest nVidia drivers.

**Comment by quixoticaxis** [comment]
Update: I've raised logging level to trace and noticed that I was trying to resize the window before the shaders and the model are loaded. If I wait for shaders and the model to load, everything works fine on the latest commit.

**Comment by quixoticaxis** [comment]
Oh, sorry, it seems it's my mistake. The tutorial commit works like it should. Also I've found where my issue lies, so I'll close the issue (I've left some code which I've added while debugging that sets the max and min sizes for the window).
Thank you for your timely response.

**Comment by adrien-ben** [comment]
Yeah models are quiet long to load on debug builds, you should try `cargo run --release`.

Nice :) Have a good time coding then !
